#*********************************************
# MakeFile Telemetria Modificato
#*********************************************

telemetriaMod: telemetriaMod.c makefile
	gcc -ansi -Wall -O telemetriaMod.c -o telemetriaMod

clean:
	rm -f telemetriaMod.o
