#*********************************************
# MakeFile CreaFile
#*********************************************

creafile: creafile.c makefile
	gcc -ansi -Wall -O creafile.c -o creafile

clean:
	rm -f creafile.o
